"""작은 수정

Revision ID: 0b92ccddb5f9
Revises: 94030140d176
Create Date: 2025-04-14 18:10:51.274659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b92ccddb5f9'
down_revision: Union[str, None] = '94030140d176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resumes_ibfk_1', 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], source_schema='recruitment', referent_schema='recruitment', onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', schema='recruitment', type_='foreignkey')
    op.create_foreign_key('resumes_ibfk_1', 'resumes', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
