"""thread_id 수정

Revision ID: 23eac27d3932
Revises: 7d3fddd9418a
Create Date: 2025-04-10 12:54:06.250414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '23eac27d3932'
down_revision: Union[str, None] = '7d3fddd9418a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('thread_id_job_recommend', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('thread_id_recruit_recommend', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('thread_id_roadmap', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('thread_id_resume_review', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('thread_id_find_study', sa.String(length=64), nullable=True))
    op.drop_column('users', 'study_thread_id')
    op.drop_column('users', 'thread_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('thread_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True))
    op.add_column('users', sa.Column('study_thread_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True))
    op.drop_column('users', 'thread_id_find_study')
    op.drop_column('users', 'thread_id_resume_review')
    op.drop_column('users', 'thread_id_roadmap')
    op.drop_column('users', 'thread_id_recruit_recommend')
    op.drop_column('users', 'thread_id_job_recommend')
    # ### end Alembic commands ###
