"""Reconstruct schema

Revision ID: 680d144bf654
Revises: 618229a47d26
Create Date: 2025-04-14 17:19:28.053668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '680d144bf654'
down_revision: Union[str, None] = '618229a47d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('user_id', sa.String(length=56), nullable=False),
    sa.Column('skill_stack', sa.JSON(), nullable=True),
    sa.Column('work_experiences', sa.Text(), nullable=True),
    sa.Column('final_degree', sa.String(length=64), nullable=True),
    sa.Column('major', sa.String(length=256), nullable=True),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('education_and_exp', sa.String(length=256), nullable=True),
    sa.Column('certificates', sa.Text(), nullable=True),
    sa.Column('awards', sa.Text(), nullable=True),
    sa.Column('languages', sa.String(length=256), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['recruitment.users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='recruitment',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.add_column('users', sa.Column('thread_id_assistant', sa.String(length=64), nullable=True))
    op.alter_column('users', 'id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=56),
               existing_nullable=False)
    op.alter_column('users', 'wanted_position',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.drop_index('ix_recruitment_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_recruitment_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'wanted_position',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=56),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'thread_id_assistant')
    op.drop_table('resumes', schema='recruitment')
    # ### end Alembic commands ###
