"""study_thread_id 추가

Revision ID: 7d3fddd9418a
Revises: 55ce2bfb197d
Create Date: 2025-04-10 11:59:19.374060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3fddd9418a'
down_revision: Union[str, None] = '55ce2bfb197d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('study_thread_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'study_thread_id')
    # ### end Alembic commands ###
