"""vector_store 칼럼 삭제

Revision ID: 8eb40eb89761
Revises: 0b92ccddb5f9
Create Date: 2025-04-16 09:17:52.595625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8eb40eb89761'
down_revision: Union[str, None] = '0b92ccddb5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resumes_ibfk_1', 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], source_schema='recruitment', referent_schema='recruitment', onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('users', 'vector_store_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vector_store_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True))
    op.drop_constraint(None, 'resumes', schema='recruitment', type_='foreignkey')
    op.create_foreign_key('resumes_ibfk_1', 'resumes', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
