"""칼럼 수정

Revision ID: 94030140d176
Revises: 680d144bf654
Create Date: 2025-04-14 18:00:23.418507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '94030140d176'
down_revision: Union[str, None] = '680d144bf654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('real_name', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('education', sa.JSON(), nullable=True))
    op.alter_column('resumes', 'work_experiences',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('resumes', 'education_and_exp',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=256),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('resumes', 'certificates',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('resumes', 'awards',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('resumes', 'languages',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=256),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint('resumes_ibfk_1', 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], source_schema='recruitment', referent_schema='recruitment', onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('resumes', 'additional_info')
    op.drop_column('resumes', 'gpa')
    op.drop_column('resumes', 'major')
    op.drop_column('resumes', 'final_degree')
    op.add_column('users', sa.Column('resume_file', sa.Text(), nullable=True))
    op.drop_column('users', 'skill_stack')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skill_stack', mysql.JSON(), nullable=True))
    op.drop_column('users', 'resume_file')
    op.add_column('resumes', sa.Column('final_degree', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True))
    op.add_column('resumes', sa.Column('major', mysql.VARCHAR(collation='utf8mb4_general_ci', length=256), nullable=True))
    op.add_column('resumes', sa.Column('gpa', mysql.DECIMAL(precision=3, scale=2), nullable=True))
    op.add_column('resumes', sa.Column('additional_info', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
    op.drop_constraint(None, 'resumes', schema='recruitment', type_='foreignkey')
    op.create_foreign_key('resumes_ibfk_1', 'resumes', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('resumes', 'languages',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=256),
               existing_nullable=True)
    op.alter_column('resumes', 'awards',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(collation='utf8mb4_general_ci'),
               existing_nullable=True)
    op.alter_column('resumes', 'certificates',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(collation='utf8mb4_general_ci'),
               existing_nullable=True)
    op.alter_column('resumes', 'education_and_exp',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=256),
               existing_nullable=True)
    op.alter_column('resumes', 'work_experiences',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(collation='utf8mb4_general_ci'),
               existing_nullable=True)
    op.drop_column('resumes', 'education')
    op.drop_column('resumes', 'summary')
    op.drop_column('resumes', 'real_name')
    # ### end Alembic commands ###
