"""음식 테이블 업데이트

Revision ID: 947a3561c855
Revises: 77764bd1cde4
Create Date: 2025-04-09 17:12:36.930547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947a3561c855'
down_revision: Union[str, None] = '77764bd1cde4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('food_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('food_name', sa.String(length=40), nullable=False),
    sa.Column('food_info', sa.String(length=40), nullable=False),
    sa.Column('food_cal', sa.Integer(), nullable=False),
    sa.Column('food_rename', sa.Integer(), nullable=True),
    sa.Column('gone', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('make_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('food_id'),
    schema='recruitment',
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food', schema='recruitment')
    # ### end Alembic commands ###
