"""Create User Table

Revision ID: e63dea5ff995
Revises: 
Create Date: 2025-04-10 10:47:44.391657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63dea5ff995'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('vector_store_id', sa.String(length=64), nullable=True),
    sa.Column('user_img', sa.Text(), nullable=True),
    sa.Column('wanted_position', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='recruitment',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_recruitment_users_id'), 'users', ['id'], unique=False, schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_users_id'), table_name='users', schema='recruitment')
    op.drop_table('users', schema='recruitment')
    # ### end Alembic commands ###
