"""skill_stack 추가

Revision ID: f04b54b035e9
Revises: 61e679b9c9dc
Create Date: 2025-04-12 22:12:27.179792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f04b54b035e9'
down_revision: Union[str, None] = '61e679b9c9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('recruit_site')
    op.add_column('users', sa.Column('skill_stack', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skill_stack')
    # op.create_table('recruit_site',
    # sa.Column('site_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('site_name', mysql.VARCHAR(length=40), nullable=False),
    # sa.Column('active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    # sa.Column('created_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    # sa.PrimaryKeyConstraint('site_id'),
    # mysql_default_charset='utf8mb3',
    # mysql_engine='InnoDB'
    # )
    # ### end Alembic commands ###
